using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Domain.HRMAdminMgt
{
    [Table("tblHRMSysPosition")]
    public class TblHRMSysPosition : AutoGeneratedIdKeyAuditableEntity<int>
    {
        [Required]
        [StringLength(20)]
        public string PositionCode { get; set; }
        [Required]
        [StringLength(100)]
        public string PositionNameEn { get; set; }
        [StringLength(100)]
        public string PositionNameAr { get; set; }
        [StringLength(500)]
        public string Description { get; set; }
    }
}
