using AutoMapper;
using CIN.Domain.HRMAdminMgt;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIN.Application.HRMAdminMgtDtos
{

    #region Position

    [AutoMap(typeof(TblHRMSysPosition))]
    public class TblHRMSysPositionDto : TblHRMSysPositionCodeDto
    {
        [Required]
        [StringLength(100)]
        public string PositionNameEn { get; set; }
        [StringLength(100)]
        public string PositionNameAr { get; set; }
        [StringLength(500)]
        public string Description { get; set; }
    }

    public class TblHRMSysPositionCodeDto : AutoGeneratedIdKeyAuditableEntityDto<int>
    {
        [Required]
        [StringLength(20)]
        public string PositionCode { get; set; }
        public bool IsDelete { get; set; }
    }

    #endregion

}
