using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CIN.Domain
{

    public abstract class PrimaryKey<T>
    {
        [Key]
        public T Id { get; set; }
    }
    public abstract class AutoGenerateIdKey<T>
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public T Id { get; set; }
    }    
    public abstract class AutoActiveGenerateIdKey<T>
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public T Id { get; set; }
        public bool IsActive { get; set; }
    }

    public abstract class AutoGenerateIdAuditableKey<T>
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public T Id { get; set; }
        [Column(TypeName = "date")]
        public DateTime? CreatedOn { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ModifiedOn { get; set; }
    }
    public abstract class AutoActiveGenerateIdAuditableKey<T> : AutoGenerateIdAuditableKey<T>
    {
        //[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        //public T Id { get; set; }
        public bool IsActive { get; set; }

        //[Column(TypeName = "date")]
        //public DateTime? CreatedOn { get; set; }
        //[Column(TypeName = "date")]
        //public DateTime? ModifiedOn { get; set; }
    }
    public abstract class AuditableActiveEntity<T> : PrimaryKey<T>
    {
        public bool IsActive { get; set; }
    }

    public abstract class AuditableEntity<T> : PrimaryKey<T>
    {
        public DateTime Created { get; set; }

        public int CreatedBy { get; set; }

        public DateTime? Modified { get; set; }

        public int ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    }
    public abstract class AuditableCreatedEntity<T> : PrimaryKey<T>
    {
        public DateTime Created { get; set; }

        public int CreatedBy { get; set; }
        public bool IsActive { get; set; }
    }
    public abstract class AutoGeneratedIdKeyAuditableCreatedEntity<T> : AutoActiveGenerateIdKey<T>
    {
        public DateTime Created { get; set; }

        public int CreatedBy { get; set; }
    }
    public abstract class AutoGeneratedIdKeyAuditableEntity<T> : AutoGenerateIdKey<T>
    {
        public DateTime CreatedDate { get; set; }

        public int CreatedBy { get; set; }

        public DateTime? ModifiedDate { get; set; }

        public int ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    }

}
