using AutoMapper;
using CIN.Application.FomMobQuery;
using CIN.Domain.FomMob;
using CIN.Domain.FomMgt;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using CIN.Application;
using Microsoft.AspNetCore.Http;

namespace CIN.Application.FomMobDtos
{
    [AutoMap(typeof(TblFomJobTicket))]
    public class TblFomJobTicketDto : ProFmAutoGeneratedIdAuditableEntityKeyDto<int>
    {
        // [StringLength(20)]
        public string TicketNumber { get; set; }
        public string CustomerCode { get; set; }
        public string CustRegEmail { get; set; }
        [StringLength(20)]
        public string SiteCode { get; set; }
        public DateTime JODate { get; set; }
        [StringLength(100)]
        public string JODocNum { get; set; }
        [StringLength(200)]
        public string JOSubject { get; set; }
        public short JOStatus { get; set; } = (short)MetadataJoStatusEnum.Open;//meta data
        public string JODescription { get; set; }
        [StringLength(20)]
        public string JODeptCode { get; set; }
        public string JOBookedBy { get; set; }
        public string ApprovedBy { get; set; }      //From UI
        public DateTime? ApprovedDate { get; set; }
        public DateTime? WorkStartDate { get; set; }
        public DateTime? ExpWorkEndDate { get; set; }
        public DateTime? ActWorkEndDate { get; set; }
        public string ClosingRemarks { get; set; }
        public string ClosedBy { get; set; }
        public string JOImg1 { get; set; }
        public string JOImg2 { get; set; }
        public string JOImg3 { get; set; }



        public string JobMaintenanceType { get; set; } = "Corrective";   //meta data--> Corrective / Planned (Metadata)
        public string JobType { get; set; }	//	meta data--> Normal,Urgent,Emergency
        public string JOSupervisor { get; set; }
        public string WorkOrders { get; set; }//String comma separated wo1, wo9, w1
        public bool IsInScope { get; set; } = false;  //will be decided by verifying Dept Code with DeptCodes in Contract
        public bool IsCreatedByCustomer { get; set; } = false;


        public bool IsOpen { get; set; } = true;
        public bool IsRead { get; set; } = false;
        public bool IsLateResponse { get; set; } = false;
        public bool IsVoid { get; set; } = false;
        public bool IsSurvey { get; set; } = false;
        public bool IsApproved { get; set; } = false;
        public bool IsConvertedToWorkOrder { get; set; } = false;
        public bool IsWorkInProgress { get; set; } = false;
        public bool IsForeClosed { get; set; } = false;
        public bool IsClosed { get; set; } = false;
        public bool IsReconcile { get; set; } = false;
        public bool IsCompleted { get; set; } = false;
        public bool IsTransit { get; set; } = false;


        public string ForecloseReasonCode { get; set; }
        public DateTime? ForecloseDate { get; set; }
        public string ForecloseBy { get; set; }
        public string CancelReasonCode { get; set; }
        public DateTime? CancelDate { get; set; }
        public string CancelBy { get; set; }

        public string QuotationNumber { get; set; }  //future purpose
        public DateTime? QuotationDate { get; set; }  //future purpose


        public bool IsQuotationSubmitted { get; set; } = false;
        public bool IsPoRecieved { get; set; } = false;
        public bool IsHold { get; set; } = false;
    }


    public class ViewTicketDto : TblFomJobTicketDto
    {
        public string Requester { get; set; }        //customerName
        public string RequesterAr { get; set; }        //customerNameAr
        public string MobileNumber { get; set; }
        public string ProjectName { get; set; }
        public string ProjectNameAr { get; set; }
        public string RequestStatus { get; set; }
        public string ServiceType { get; set; }
        public string ServiceTypeAr { get; set; }
        public string ServiceCategory { get; set; }
        public string ServiceCategoryAr { get; set; }
        public string Image1WithFullPath { get; set; }
        public string Image2WithFullPath { get; set; }
        public string Image3WithFullPath { get; set; }



    }
    public class InputTblFomJobTicket
    {
        public int Id { get; set; }
        //  public string TicketNumber { get; set; }
        public string CustomerCode { get; set; }
        public string SiteCode { get; set; }
        public DateTime? JODate { get; set; }

        public string JOSubject { get; set; }
        public string JODescription { get; set; }
        public string JODeptCode { get; set; }
        public string JOBookedBy { get; set; }
        public string ApprovedBy { get; set; }      //From UI

        public string JobMaintenanceType { get; set; } = "Corrective";   //meta data--> Corrective / Planned (Metadata)
        public bool IsInScope { get; set; } = true;
        public string JobType { get; set; }	//	meta data--> Normal,Urgent,Emergency
        public string JOSupervisor { get; set; }
        public string Base64Image1 { get; set; }
        public string Base64Image2 { get; set; }
        public string Base64Image3 { get; set; }
        public string WebRoot { get; set; }
    }
    public class InputJobTicketFromCustomerPortalDto : InputTblFomJobTicket
    {
        public IFormFile Image1IForm { get; set; }
        public IFormFile Image2IForm { get; set; }
        public IFormFile Image3IForm { get; set; }
    }
    public class InputCreateUpdateJobTicketDto : InputJobTicketFromCustomerPortalDto
    {
        public bool IsFromMobile { get; set; } = false;
        public bool IsFromWeb { get; set; } = false;
    }

    public class InputCreateUpdateB2CJobTicketDto : InputCreateUpdateJobTicketDto
    {
        public string TicketNumber { get; set; }
        public string Response { get; set; }
        public string TokenNumber { get; set; }
        public decimal GeoLatitude { get; set; }
        public decimal GeoLongitude { get; set; }
        public string TimeValue { get; set; }
        public int ContractId { get; set; }
        public string ServiceType { get; set; }
    }


    public class InputAddJobTicketNotesDto
    {
        public string TicketNumber { get; set; }
        public string Note { get; set; }
    }
    public class FrontOfficeB2CTicketDto
    {
        [Required]
        public string TicketNumber { get; set; }
        [Required]
        public string ActionType { get; set; }
        public string ReasonCode { get; set; }
    }

    public class JobTicketNotesListDto : InputAddJobTicketNotesDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public DateTime CreatedOn { get; set; }
    }

    public class GetProjectOpenTicketsListDto
    {
        public LanCustomSelectListItem Total { get; set; }
        public List<LanCustomSelectListItem> List { get; set; }
    }

    public class InputUpdateJobTicketServiceTypeDto
    {
        public string TicketNumber { get; set; }
        public string JobMaintenanceType { get; set; }
    }
    public class InputChangeStatusJobTicketDto
    {
        public string TicketNumber { get; set; }
        public string ReasonCode { get; set; }
    }
    public class InputPoRecevedForTicketDto
    {
        public string TicketNumber { get; set; }
        public string PoNumber { get; set; }
    }

    public class InputCompleteJobTicketDto
    {
        public string TicketNumber { get; set; }

    }

    public class InputCloseJobTicketDto
    {
        public string TicketNumber { get; set; }
        public string Base64Image1 { get; set; }
        public string Base64Image2 { get; set; }
        public string Base64Image3 { get; set; }
        public string WebRoot { get; set; }
        public string ClosingRemarks { get; set; }
    }


    public class RecentTicketsDto : TblFomJobTicketDto
    {
        public string DepNameEng { get; set; }
        public string DepNameArb { get; set; }
        public string CustomerNameEng { get; set; }
        public string CustomerNameArb { get; set; }
        public string ProjectNameEng { get; set; }
        public string ProjectNameArb { get; set; }
        public int LogNotesCount { get; set; }
        public string StatusStr { get; set; }
    }
    public class RecentUserTicketsDto : RecentTicketsDto //Supv & Mnager
    {

    }
    public class RecentB2CTicketsDto : RecentUserTicketsDto //Supv & Mnager
    {
        public decimal GeoLatitude { get; set; }
        public decimal GeoLongitude { get; set; }
        public TimeSpan OnlyTime { get; set; }
        public string TimeValue { get; set; }
    }
    public class TicketReportDetailsDto : RecentUserTicketsDto
    {
        public string WorkLocation { get; set; }
        public string WorkDescrption { get; set; }
        public string Supervisor { get; set; }
    }

    public class InputPaginationCommon
    {
        public int Page { get; set; } = 0;
        public int PageCount { get; set; } = 10;
        public string Query { get; set; } = string.Empty;
        public string OrderBy { get; set; } = "id desc";
    }

    public class InputTicketsPaginationFilterDto : InputPaginationCommon
    {

        public string TicketNumber { get; set; }
        public string CustomerCode { get; set; }
        public string SiteCode { get; set; }
        public string Supervisor { get; set; }
        public string StatusStr { get; set; }      //incomplete,outofscope
        public int? Status { get; set; }
        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }

    }

    public class InputUserTicketsPaginationFilterDto : InputTicketsPaginationFilterDto
    {
        public string ProjectName { get; set; }
        public string JODeptCode { get; set; }
        public string ServiceType { get; set; }
        public string MaintanceType { get; set; }
    }

    public class InputScopewiseTicketsPaginationFilterDto : InputPaginationCommon
    {
        public string ScopeType { get; set; } = "all";   //inscope,outscope,all
        public int? Status { get; set; } = null;
        public string StatusSearch { get; set; }   //static string as input
    }



    public class InputFomMobDashboardDataForClientDto
    {
        public string SiteCode { get; set; }
    }

    public class OutputFomMobDashboardDataForClientDto
    {
        public List<DepWiseIncompleteTicketsCount> DepWiseUnfinishedServices { get; set; } = new();
        public List<StatusWiseAllTicketsCount> StatusWiseTickets { get; set; } = new();

    }
    public class DepWiseIncompleteTicketsCount
    {
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentNameAr { get; set; }
        public int Count { get; set; } = 0;
    }
    public class StatusWiseAllTicketsCount
    {
        public string SatatusStr { get; set; }
        public int Count { get; set; } = 0;
        public decimal Percentage { get; set; } = 0;
    }


}
