export interface TblSndDefCustomerMasterDto {
  custCode:string;
  custName: string;
  custArbName: string;
  custAlias: string;
  custType: number;
  custCatCode: string;
  custRating: number;
  salesTermsCode: string;
  custDiscount: number;
  custCrLimit: number;
  custSalesRep: string;
  custSalesArea: string;
  custARAc: number;
  custLastPaidDate: string;
  custLastSalesDate: string;
  custLastPayAmt: number;
  custAddress1: string;
  custCityCode1: string;
  custMobile1: string;
  custPhone1: string;
  custEmail1: string;
  custContact1: string;
  custAddress2: string;
  custCityCode2: string;
  custMobile2: string;
  custPhone2: string;
  custEmail2: string;
  custContact2: string;
  custUDF1: string;
  custUDF2: string;
  custUDF3: string;
    custAllowCrsale:boolean;
    custAlloCrOverride:boolean;
    custOnHold:boolean;
    custAlloChkPay:boolean;
    custSetPriceLevel:true;
  custPriceLevel: number;
    custIsVendor:boolean;
    custArAcBranch:true;
  custArAcCode: string;
  custDefExpAcCode: string;
  custARAdjAcCode: string;
  custARDiscAcCode: string;
    stateone:string;
    countryone:string;
    statetwo:string;
    countrytwo:string;
    isActive:true;
    id:number;
    createdOn:string;
    modifiedOn:string
  }
