using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace CIN.Application
{
    public abstract class PrimaryKeyDto<T>
    {
        public T Id { get; set; }
    }
    public abstract class AutoGenerateIdKeyDto<T>
    {        
        public T Id { get; set; }
    }
    public abstract class AutoActiveGenerateIdKeyDto<T> : AutoGenerateIdKeyDto<T>
    {                
        public bool IsActive { get; set; }
    }

    public abstract class AutoGenerateIdAuditableKeyDto<T>
    {       
        public T Id { get; set; }
        [Column(TypeName = "date")]
        public DateTime? CreatedOn { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ModifiedOn { get; set; }
    }
    public abstract class AutoActiveGenerateIdAuditableKeyDto<T> : AutoGenerateIdAuditableKeyDto<T>
    {
        public bool IsActive { get; set; }
    }
    public abstract class AuditableActiveEntityDto<T> : PrimaryKeyDto<T>
    {
        public bool IsActive { get; set; }
    }


    public abstract class AuditableEntityDto<T> : PrimaryKeyDto<T>
    {
        public DateTime Created { get; set; }

        public int CreatedBy { get; set; }

        public DateTime? Modified { get; set; }

        public int ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    }
    public abstract class AuditableCreatedEntityDto<T> : PrimaryKeyDto<T>
    {
        public DateTime Created { get; set; }

        public int CreatedBy { get; set; }
        public bool IsActive { get; set; }
    }
    public abstract class AutoGeneratedIdKeyAuditableEntityDto<T> : AutoGenerateIdKeyDto<T>
    {
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    }
}
